name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-secure-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      run: docker build . --file dockerfile --tag my-image-name:Labo2

    - name: Scan image
      uses: Azure/container-scan@v0
      with:
        image-name: my-image-name:Labo2
        severity-threshold: CRITICAL
        run-quality-checks: true
        continue-on-error: true

    - name: Login to the Container Registry  
      uses: azure/docker-login@v1
      with:
        login-server: contoso.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    - name: Push image
      run: |
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/spring-petclinic:${{ github.run_number }}

      
   
    
   
