name: Push Docker image to Azure Container Registry

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-secure-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      run: docker build . --file dockerfile --tag ${{ secrets.ACR_LOGIN_SERVER }}/my-image-name:docker-azure

    - name: Scan image
      uses: Azure/container-scan@v0
      with:
        image-name: ${{ secrets.ACR_LOGIN_SERVER }}/my-image-name:docker-azure
        severity-threshold: CRITICAL
        run-quality-checks: true

    - name: Login to the Container Registry  
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    - name: Push Docker image to Azure Container Registry
      run: |
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/my-image-name:docker-azure
